version: "3.8"

services:
    server:
        build:
            context: apps/server
            dockerfile: Dockerfile
        container_name: aworldaway-server
        ports:
            - "${SERVER_PORT:-8000}:8000"
        environment:
            - DEBUG=${DEBUG:-false}
            - HOST=0.0.0.0
            - PORT=8000
            - PYTHONUNBUFFERED=1
        volumes:
            - ./apps/server/models:/app/models:ro
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 10s
        restart: unless-stopped
        networks:
            - aworldaway-network

    web:
        build:
            context: apps/web
            dockerfile: Dockerfile
        container_name: aworldaway-web
        ports:
            - "${WEB_PORT:-3000}:3000"
        environment:
            - NODE_ENV=production
            - NUXT_PUBLIC_API_BASE_URL=${API_BASE:-http://server:8000}
        depends_on:
            server:
                condition: service_healthy
        healthcheck:
            test:
                [
                    "CMD",
                    "wget",
                    "--no-verbose",
                    "--tries=1",
                    "--spider",
                    "http://localhost:3000",
                ]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 10s
        restart: unless-stopped
        networks:
            - aworldaway-network

networks:
    aworldaway-network:
        driver: bridge

volumes:
    models-data:
        driver: local
